#!/bin/sh
exec 2>&1

if [ -f /etc/td-agent/td-agent.conf ]; then
  exec /sbin/setuser root /usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --use-v1-config
else
  echo 'td-agent not configured'
fi
